# Generated by Django 3.2.4 on 2021-07-14 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineID', models.TextField()),
                ('groupID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.TextField()),
                ('createDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.TextField()),
                ('JobDetial', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('NextLVReqExp', models.IntegerField()),
                ('TotalExp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineID', models.TextField()),
                ('userLevel', models.IntegerField()),
                ('userAmount', models.FloatField()),
                ('userPermissions', models.IntegerField(choices=[(100, 'Admin'), (30, 'Common Member'), (0, 'New Member')])),
                ('createDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.TextField()),
                ('SkillOnAP', models.TextField()),
                ('SkillValue', models.IntegerField()),
                ('SkillMP', models.IntegerField()),
                ('SkillDetial', models.TextField()),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageAPI.job')),
            ],
        ),
        migrations.CreateModel(
            name='RoleData',
            fields=[
                ('RoleID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creatorLineId', models.TextField()),
                ('RoleName', models.TextField()),
                ('RoleLevel', models.IntegerField()),
                ('RoleExp', models.IntegerField()),
                ('RoleTolExp', models.BigIntegerField()),
                ('FriendListID', models.BigIntegerField()),
                ('GuildID', models.BigIntegerField()),
                ('EquipmentID', models.BigIntegerField()),
                ('RoleCreateDateTime', models.DateTimeField()),
                ('HP', models.IntegerField()),
                ('MP', models.IntegerField()),
                ('Str', models.IntegerField()),
                ('Dex', models.IntegerField()),
                ('Vit', models.IntegerField()),
                ('Spi', models.IntegerField()),
                ('JusticeValue', models.IntegerField()),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MessageAPI.job')),
            ],
        ),
    ]
